### ISSUE TITLE
Older feature implementations take precedence over disabled features

### ISSUE THREAD

**Issue by indrekpaas** [keithclark/css-feature-toggle-devtools-extension#14]
I stumbled upon an issue where older implementations of specific values take precedence over the `-disabled-*` values. This has to do with this extension's features not including older implementations consistently.

![image](https://user-images.githubusercontent.com/6239035/52023528-84acb300-2551-11e9-962f-9be3e18713a6.png)

Cheers

**Comment by keithclark** [comment]
Fixed in #22. Thanks for your help @indrekpaas
