### ISSUE TITLE
Add toggle selected options button

### ISSUE THREAD

**Issue by b-strauss** [keithclark/css-feature-toggle-devtools-extension#21]
For example: when I disable both flexbox and grid layout, I want to toggle both of these at the same time.

**Comment by keithclark** [comment]
Could you elaborate a little on how you see this working?

**Comment by b-strauss** [comment]
If I have a set of checked disabled features (for example flex, grid, and sticky), and I want to switch fast between the default state (all unchecked) and my set, it's a bit cumbersome to deactivate all 3 and after I checked the layout activate those 3 again. This button would activate/deactivate those 3 at the same time with a single click. If I change the set by selecting an additional feature (for example by adding transforms) and removing one (for example grid). The button would now toggle all checkboxes of this new feature set. It basically switches all currently selected checkboxes and remembers those which where last active.

**Comment by keithclark** [comment]
Feature toggling is now in v1.0.2
