### ISSUE TITLE
disable css custom properties

### ISSUE THREAD

**Issue by sturobson** [keithclark/css-feature-toggle-devtools-extension#3]
Hey Keith -- thanks for this dev tools extension - it's already proving invaluable to test what the layouts of my clients sites would look like when there's no grid and/or no flex available (we still need to 'support' IE11).

I was wondering how easy it would be to add an option to disable css custom properties. Having a quick look in how you're turning other CSS features on and off I don't think it's as simple as 'copy, paste, change a few things'.

It would be really neat to have the options to:

- disable all CSS custom properties
- disable the first custom properties in a `var()` to show the fallback.

I'll try and carve some time out to see if I can fudge this together.

**Comment by keithclark** [comment]
@sturobson This ability to disable all custom properties is in this [PR](#4). Could you checkout the [css-function-support branch](https://github.com/keithclark/css-feature-toggle-devtools-extension/tree/css-function-support) and see if it suits your needs for the first point?

Regarding the 2nd point; I think I know what you're after but, for the sake of clarity, could you give me an example of what you'd like to see? Ideally something I can use as a test case.

**Comment by sturobson** [comment]
This is working great for me for disabling all custom properties. Thanks so much :))

I'll try and explain what I mean in my second point as soon as I've some free time.

This is working perfectly for now

**Comment by keithclark** [comment]
Great. I'll close this issue off and get the PR merged. When you're ready, can you create a new issue for the other request?
